name: C/C++ CI

on:
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: instalando cppcheck
      run: sudo apt-get install cppcheck
    - name: executando cppcheck
      run: cppcheck --enable=all Conta.cpp Banco.cpp main.cpp
      
    - name: Step - Use the upload Artifact Github Action
      uses: actions/upload-artifact@v3
      with:
        name: bancoAtualizado
        path: /home/runner/work/parte1Projeto/parte1Projeto/
